version: '2'
services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: ws
    restart: always
    ports:
      - '80'
      - '631'
    links:
      - mydb
    volumes:
      - './www:/var/www/html'
      - './config/php/php.ini:/usr/local/etc/php/php.ini'
      - './config/vhosts:/etc/apache2/sites-enabled'
      - './config/apache2/ports.conf:/etc/apache2/ports.conf'
      - './config/cups:/etc/cups'
      - './logs/apache2:/var/log/apache2'
      - './logs/cups:/var/log/cups'
      - './driver:/root/driver'
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      macvlan66:
        ipv4_address: 192.168.66.2
  mydb:
    image: mariadb
    container_name: db
    user : "1000:1000"
    restart: always
    ports:
      - '3306'
    volumes:
      - './config/mysqld:/etc/mysql/conf.d'
      - './mysql:/var/lib/mysql'
      - './logs/mysql:/var/log/mysql'
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - MYSQL_ROOT_PASSWORD=blackant
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON
    networks:
      macvlan69:
        ipv4_address: 192.168.69.2
networks:
  macvlan66:
    external:
      name: macvlan66
  macvlan69:
    external:
      name: macvlan69