version: '3'
services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: webserver
    hostname: webserver
    restart: always
    ports:
      - '80'
      - '631'
    links:
      - mydb
    volumes:
      - './www:/var/www/html'
      - './config/php/php.ini:/usr/local/etc/php/php.ini'
      - './config/vhosts:/etc/apache2/sites-enabled'
      - './config/apache2/ports.conf:/etc/apache2/ports.conf'
      - './config/cups:/etc/cups'
      - './logs/apache2:/var/log/apache2'
      - './logs/cups:/var/log/cups'
      - './driver:/root/driver'
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      ws_net:
        ipv4_address: 192.168.66.2
  mydb:
    image: mariadb
    container_name: database
    hostname: database
    user : "1000:1000"
    restart: always
    ports:
      - '3306'
    volumes:
      - './config/mysqld:/etc/mysql/conf.d'
      - './mysql:/var/lib/mysql'
      - './logs/mysql:/var/log/mysql'
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - MYSQL_ROOT_PASSWORD=blackant
    command: mysqld --innodb-flush-method=littlesync --innodb-use-native-aio=OFF --log_bin=ON
    networks:
      db_net:
        ipv4_address: 192.168.69.2
  networks:
    ws_net:
      ipam:
        name : macvlan66
        driver: macvlan
        driver_opts:
          parent: vmbr0
        config:
         - subnet:   "192.168.66.0/24"
           gateway:  "192.168.66.1"
           ip_range: "192.168.66.0/24"
    db_net:
      ipam:
        name : macvlan69
        driver: macvlan
        driver_opts:
          parent: vmbr0
        config:
         - subnet:   "192.168.69.0/24"
           gateway:  "192.168.69.1"
           ip_range: "192.168.69.0/24"